select * from EMP
SELECT * FROM EMP WHERE ENAME='CLARK'
SELECT * FROM EMP WHERE JOB='MANAGER'
SELECT * FROM EMP WHERE HIREDATE>'2021-01-24'
SELECT * FROM EMP WHERE JOB='MANAGER' OR  JOB='SALESMAN'
SELECT * FROM EMP WHERE SAL>200 AND SAL<200
SELECT * FROM EMP WHERE SAL>200
select * from EMP
CREATE TABLE DEPT
(
DEPTNO NUMERIC(2),DNAME VARCHAR(20),LOC VARCHAR(14))
INSERT INTO DEPT VALUES('10','ACCOUNTING','NEWYORK')
INSERT INTO DEPT VALUES('20','RESEARCH','DALLASE')
INSERT INTO DEPT VALUES('30','SALES','CHICAGO')
INSERT INTO DEPT VALUES(40,'OPERATIONS','BOSTON')
SELECT * FROM DEPT
INSERT INTO DEPT VALUES(50,'TECHNICIAN','EUROPE')
INSERT INTO DEPT VALUES(60,'DEVOLOPER','AMERICA')
select  * from emp where EMPNO in(1,2)
select  * from emp where EMPNO in(7369,7499,7782)
select * from EMP where EMPNO=7369 OR EMPNO=7499
select * from EMP where EMPNO=7369 AND EMPNO=7499
select * from EMP where EMPNO BETWEEN 7369 AND 7844
 select * from EMP where EMPNO BETWEEN 7844 AND 7369
 CREATE TABLE STUDENT(ID NUMERIC,NAME VARCHAR(20),S1 TINYINT,S2 TINYINT,S3 TINYINT)
 INSERT INTO STUDENT VALUES(10,'VINOD','35','35','60'),(11,'JANAKI','65','45','98')
 INSERT INTO STUDENT VALUES(12,'UDAY','25','55','34')
 SELECT * FROM STUDENT
 SELECT * FROM STUDENT WHERE S1>=35 AND S2>=35 AND S3>=35
  SELECT * FROM STUDENT WHERE S1>=35 OR S2>=35 OR S3>=35

 CREATE TABLE SALGRADE
(
GRADE NUMERIC,
LOSAL NUMERIC,
HISAL NUMERIC
);
INSERT INTO SALGRADE VALUES (1,  700, 1200);
INSERT INTO SALGRADE VALUES (2, 1201, 1400);
INSERT INTO SALGRADE VALUES (3, 1401, 2000);
INSERT INTO SALGRADE VALUES (4, 2001, 3000);
INSERT INTO SALGRADE VALUES (5, 3001, 9999);
COMMIT;
SELECT * FROM EMP
SELECT * FROM EMP WHERE JOB IN('CLERK','MANAGER') AND SAL BETWEEN 500 AND 2000
SELECT * FROM EMP WHERE JOB ='MANAGER'